### ISSUE TITLE
Evaluierung von Lösungen für swib.org-Mailadressen, die die jeweils Zuständigen erreichen

### ISSUE THREAD

**Issue by acka47** [swibcon/swib-orga#13]
Beispielhafte Anwendungsfälle werden in https://github.com/swibcon/swib.org/issues/5 genannt:

> - [coc@swib.org](mailto:coc@swib.org) with automatic forwarding to hbz and ZBW marketing
> - [pc-chairs@swib.org](mailto:pc-chairs@swib.org) redirecting to @annakasprzik's and my email

**Comment by acka47** [comment]
@Phu2 Du hast dich ja bei metadaten.community mit Mailversand etc. auseinandergesetzt. Gäbe es da für diesen Anwendungsfall vielleicht eine einfache Lösung?

**Comment by Phu2** [comment]
Für metadaten.community haben wir einen neuen Mailserver aufgesetzt, weil die vorhandenen Mailserver nur für hbz-Adressen zuständig sein sollen. Im Prinzip können wir den neuen Mailserver auch für swib.org-Adressen verwenden. Ich werde das mal mit unserer ZIT besprechen.

**Comment by Phu2** [comment]
Wahrscheinlich verwandt: https://github.com/swibcon/swib.org/issues/5

**Comment by acka47** [comment]
> Wahrscheinlich verwandt: https://github.com/swibcon/swib.org/issues/5

In der Tat. Ich mache das mal zu.

**Comment by Phu2** [comment]
Die Nutzung des neuen Mailservers `oi-smtp-proxy` für swib.org ist mit der ZIT abgetimmt und ein erster lokaler Test erfolgreich gewesen. Jetzt muss die ZIT noch die DNS-Einträge für swib.org anpassen/ergänzen.

**Comment by Phu2** [comment]
> [coc@swib.org](mailto:coc@swib.org) with automatic forwarding to hbz and ZBW marketing

An welche Adressen soll weitergeleitet werden?

**Comment by acka47** [comment]
> An welche Adressen soll weitergeleitet werden

Das müssten wir für coc@swib.org noch klären. Zum Testen kannst du gerne mal die Weiterleitung von pc-chairs@swib.org auf Annas und meine Adresse einrichten.

**Comment by Phu2** [comment]
DNS-Einträge sind verfügbar, Testmail an pc-chairs@swib.org und postmaster@swib.org versendet und angekommen.

**Comment by acka47** [comment]
Super! Danke, @Phu2 . Dann schließe ich mal das Ticket, in dem wir jetzt nicht nur "Lösungen evaluiert", sondern direkt eine Lösung umgesetzt haben. Wir melden uns, sobald eine weitere E-Mail-Weiterleitung eingerichtet werden soll.

**Comment by Phu2** [comment]
Weitere E-Mail-Weiterleitungen müssen in der /etc/postfix/virtual eingetragen werden. Anschließend:
`postmap lmdb:/etc/postfix/virtual`
`postfix check`
`postfix reload`

**Comment by Phu2** [comment]
team@swib.org hinzugefügt, Weiterleitung an @acka47 und @Phu2
